# .github/workflows/deploy.yml

name: Deploy Game to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el código de tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Reemplaza los placeholders y MUESTRA EL RESULTADO
      - name: Replace EmailJS Credentials and Debug
        run: |
          echo "--- Contenido de game.js ANTES de reemplazar ---"
          cat game.js
          echo "------------------------------------------------"

          sed -i 's/EMAILJS_USER_ID_PLACEHOLDER/${{ secrets.EMAILJS_USER_ID }}/g' game.js
          sed -i 's/EMAILJS_SERVICE_ID_PLACEHOLDER/${{ secrets.EMAILJS_SERVICE_ID }}/g' game.js
          sed -i 's/EMAILJS_TEMPLATE_ID_PLACEHOLDER/${{ secrets.EMAILJS_TEMPLATE_ID }}/g' game.js

          echo "--- Contenido de game.js DESPUÉS de reemplazar ---"
          cat game.js
          echo "-------------------------------------------------"

      # 3. Despliega la carpeta completa a la rama 'gh-pages'
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
